### ISSUE TITLE
ihtishamsudo - StakeEXA.permitandDeposit can be DoSed by front-running user and performing the permit()

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-07-exactly-stacking-contracts-judging#3]
ihtishamsudo

Medium

# StakeEXA.permitandDeposit can be DoSed by front-running user and performing the permit()

## Summary
The `StakedEXA` contract having a vulnerability in its `permitAndDeposit` function that makes it susceptible to front-running attacks. This vulnerability could lead to Denial of Service (DoS) for users attempting to deposit funds using the permit functionality.

## Vulnerability Detail
The `permitAndDeposit` function combines an EIP-2612 permit call with a deposit action in a single transaction. However, it does not implement any protection against front-running attacks. An attacker can observe the transaction in the mempool, extract the permit signature, and execute a separate permit transaction before the original `permitAndDeposit` transaction is processed.

StakedEXA is using `OZ` ERC20PermitUpgradeable which clearly states about using permit function: 

```solidity
 ==== Security Considerations
 *
 * There are two important considerations concerning the use of `permit`. The first is that a valid permit signature
 * expresses an allowance, and it should not be assumed to convey additional meaning. In particular, it should not be
 * considered as an intention to spend the allowance in any specific way. The second is that because permits have
 * built-in replay protection and can be submitted by anyone, they can be frontrun. A protocol that uses permits should
 * take this into consideration and allow a `permit` call to fail. Combining these two aspects, a pattern that may be
 * generally recommended is:
 *
 * 
 * function doThingWithPermit(..., uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s) public {
 *     try token.permit(msg.sender, address(this), value, deadline, v, r, s) {} catch {}
 *     doThing(..., value);
 * }
 *
 * function doThing(..., uint256 value) public {
 *     token.safeTransferFrom(msg.sender, address(this), value);
 *     ...
 * }
```

## Impact
The primary impact of this vulnerability is potential Denial of Service (DoS) for users. When a user attempts to use the `permitAndDeposit` function, their transaction may fail due to a front-running attack. This can result in:

- Failed deposits, preventing users from staking their tokens.

## Code Snippet
[function permitAndDeposit](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/3eb87e3edf3bcd57c4cc1c6a73e8255f575b76de/protocol/contracts/StakedEXA.sol#L173)
```solidity
function permitAndDeposit(uint256 assets, address receiver, Permit calldata p) external returns (uint256) {
  IERC20Permit(asset()).permit(msg.sender, address(this), p.value, p.deadline, p.v, p.r, p.s);
  return deposit(assets, receiver);
}
```

## Tool used
Manual Review

## Recommendation
To mitigate this vulnerability, implement a try-catch block around the permit call. the use of `try/catch` allows the permit to fail and makes the code tolerant to frontrunning.

```diff
function permitAndDeposit(uint256 assets, address receiver, Permit calldata p) external returns (uint256) {
-  IERC20Permit(asset()).permit(msg.sender, address(this), p.value, p.deadline, p.v, p.r, p.s);
+ try IERC20Permit(asset()).permit(msg.sender, address(this), p.value, p.deadline, p.v, p.r, p.s) {} catch {}
  return deposit(assets, receiver);
}
```

**Comment by TradMod** [comment]
Escalate!

**Comment by sherlock-admin3** [comment]
> Escalate! 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ihtisham-sudo** [comment]
Thanks @ShaheenRehman for escalating on my behalf.

> Low/Info; For an issue to be a valid DoS:
> 
> > The issue impacts the availability of time-sensitive functions

Indeed, permitAndDeposit function is time-sensitive due to the nature of EIP-2612 permits, which have expiration deadlines. Front-running attacks can cause these permits to fail, effectively making the function unavailable within its intended timeframe. This directly impacts availability, as users cannot execute their intended actions within the expected and often narrow time window of their permit's validity.

> and because users can still call `deposit()` directly, so depositing into the system still works.

While it's true that users can call deposit() directly, but the permitAndDeposit() function serves a specific purpose - allowing users to approve and deposit in a single transaction. Compromising this significantly impacts the functionality of protocol that is not working as intended.

it should be considered M and it has always been judged as Valid M is past contests.

Thanks

**Comment by WangSecurity** [comment]
But, can't the user call `permitAndDeposit` in the next block and successfully deposIt?

**Comment by ihtisham-sudo** [comment]
While the user could theoretically call `permitAndDeposit` in the next block, but it's overlooking that : 

- Front-running or griefing can be repeated, potentially blocking the user across multiple blocks.
- In volatile markets, even a single block delay can result in significant financial losses or missed opportunities.
- The permit's deadline may expire, forcing the user to generate a new signature, which is especially problematic for smart contract wallets or offline signing setups.

The reason that this should be M is because an innocent user can be griefed for multiple blocks or for as long as malicious attacker want and this fall in the category of DoS as per sherlock rules: 
> Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue.

Here's blog post by trust in which this issue is explained in details: 
[Blog Link](https://www.trust-security.xyz/post/permission-denied)

**Comment by WangSecurity** [comment]
> Front-running or griefing can be repeated, potentially blocking the user across multiple blocks

This argument is invalid based on the rule you quoted, it's considered a one-block DOS.

>  volatile markets, even a single block delay can result in significant financial losses or missed opportunities

I think this argument is vague and the deposit function is not "clearly" time-sensitive.

> The permit's deadline may expire, forcing the user to generate a new signature, which is especially problematic for smart contract wallets or offline signing setups

This is the users' responsibility if they set the permit's deadline for only one block when it's 2 seconds on Optimism on average. Also, it's user's responsibility if their permit creation takes too long.

Hence, I believe this should be invalid as it's a DOS of one block for not time-sensitive function. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts-judging/issues/3/#issuecomment-2278011730): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/exactly/protocol/pull/757

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
